version: '3.4'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:rw,cached
    networks:
      - dev_net
    ports:
      - target: 80
        published: 8080
        protocol: tcp

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - dev_net

networks:
  dev_net:
    external: true
