version: '3.4'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:rw,cached
    networks:
      - dev_net
    ports:
      - target: 80
        published: 8080
        protocol: tcp

networks:
  dev_net:
    external: true
