version: '3.4'

services:
  backend:
    container_name: f1_backend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:rw,cached
    networks:
      - dev_net
    ports:
      - target: 80
        published: 8080
        protocol: tcp

  postgres:
    container_name: f1_postgres
    image: postgres:16.2
    networks:
      - dev_net
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root

networks:
  dev_net:
    external: true
